title: My Cool Blog
author: Emma Estberg
email: estberg dot hope at gmail dot com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my blog ! You'll find all my thoughts here, on anything and everything. Hope you enjoy!

# social links
instagram_username: emma.est
github_username:  emmaestberg

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
